apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: "ganapati"
  name: "cool-binding"
  namespace: "default"
subjects:
  - kind: ServiceAccount
    name: "ga-ganapati"
    namespace: "default"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "cool-role"

